### ISSUE TITLE
Directory permission error

### ISSUE THREAD

**Issue by julesbike** [Serene-Arc/podcast-downloader#5]
Hi I don't know if this project is still being maintained but I am having some problems.

Firstly the example you give in the readme does not seem to be correct I have had to add the word download as a command.

I then get a permission error:

```
openhabian@openhabian:/ $ python -m podcastdownloader download / -l 1 -v -f 'https://anchor.fm/s/3cbbb3b8/podcast/rss'
[2022-10-06 18:06:06,180 - root - INFO] - 1 feeds found
[2022-10-06 18:06:06,184 - root - DEBUG] - Beginning retrieval for https://anchor.fm/s/3cbbb3b8/podcast/rss
[2022-10-06 18:06:14,293 - root - INFO] - Retrieved RSS for The WAN Show
[2022-10-06 18:06:14,294 - root - INFO] - All feeds filled
[2022-10-06 18:06:14,295 - root - INFO] - Limiting episodes per podcast to 1 entries
[2022-10-06 18:06:14,296 - root - INFO] - 1 episodes to download
[2022-10-06 18:06:14,297 - root - DEBUG] - Attempting download of episode USB Branding Changed Again... - WAN Show September 30, 2022 in The WAN Show
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/openhabian/.local/lib/python3.9/site-packages/podcastdownloader/__main__.py", line 173, in <module>
    cli()
  File "/home/openhabian/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/openhabian/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/openhabian/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/openhabian/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.9/site-packages/podcastdownloader/__main__.py", line 118, in cli_download
    asyncio.run(download_episodes(all_feeds, destination, threads, write_playlist, limit))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/openhabian/.local/lib/python3.9/site-packages/podcastdownloader/__main__.py", line 168, in download_episodes
    await asyncio.gather(*episode_downloaders)
  File "/home/openhabian/.local/lib/python3.9/site-packages/podcastdownloader/__main__.py", line 77, in download_individual_episode
    await episode.download(session)
  File "/home/openhabian/.local/lib/python3.9/site-packages/podcastdownloader/episode.py", line 89, in download
    self.file_path.parent.mkdir(exist_ok=True, parents=True)
  File "/usr/lib/python3.9/pathlib.py", line 1312, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/The WAN Show'
```

**Comment by Serene-Arc** [comment]
Hi, sorry for the late response. I stopped working on this project in the middle of a rewrite but I'm coming back to it as I use it.

The issue here seems to be that you're attempting to write to a path that comes from the root `/`. You need to be root to do that. You either need to run this as root, use sudo, or (the best option) choose another directory to write to.
